baseURL = 'https://temaelkin.github.io/uni-portfolio/'
languageCode = 'en-us'
title = 'Tema Elkin'
theme = 'archie'

[params]
mode = "auto"
useCDN = false
subtitle = "Portfolio. Herzen University (RSPU)"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/temaelkin"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3