baseURL = 'https://temaelkin-uni.github.io/'
languageCode = 'en-us'
title = 'Tema Elkin'
theme = 'archie'

[params]
mode = "auto"
useCDN = false
subtitle = "Uni portfolio"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/temaelkin"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2
